### ISSUE TITLE
[BUG]年龄正溢出时程序闪退

### ISSUE THREAD

**Issue by debuggerzh** [misterplus/LearnWithEase#16]
**简述**
在尝试填入一个足够大的年龄后点击注册，程序立刻闪退后并重启
**重现步骤**
重现该Bug所需的步骤：
1. 在“请输入年龄”一栏填入一个足够大的年龄，如22446744073709551615
2. 其他信息均合法，保持网络与服务器开启，点击注册

**预期行为**
提示“请输入正确年龄”

**实际行为**
程序闪退并重启

**版本**
将测试时使用的app版本与appserver版本(commit号)粘贴在这里。
app:https://github.com/misterplus/LearnWithEase/commit/674b9f40e2e4583c5f2efc233ce49af2466aa501
server:https://github.com/misterplus/LearnWithEaseServer/commit/c779ceabf65d4298a9cd83017663707baa1f3c55

**解决方案**
增加对年龄字段长度的限制约束

**Comment by misterplus** [comment]
Closed via https://github.com/misterplus/LearnWithEase/pull/13/commits/e56c27f9cbca4e3417e06d5fd78c2d1b91a02460
