### ISSUE TITLE
[Test Report]注册拾遗

### ISSUE THREAD

**Issue by debuggerzh** [misterplus/LearnWithEase#18]
**简述**

对客户端注册模块的补充

**测试流程**
单次测试流程的所有执行步骤：

0. 进入登陆界面,点击新用户注册,进入注册界面
1. 填入下表中的信息,其他信息保持默认值
2. 点击注册,观察响应情况

**测试案例**
以成组的方式，分别描述测试数据，测试结果，预期结果

| 用户名    | 密码       | 昵称  | 年龄 | 所在城市           |
| --------- | ---------- | ----- | ---- | ------------------ |
| dediaocha | as8975asdf | debug | 12   | 北京市北京市东城区 |
| debug1| 1234asdf | debug | 12   | 新疆维吾尔自治区伊犁哈萨克自治州察布查尔锡伯自治县 |

测试结果:显示注册中,几秒钟后账号成功注册

预期结果:账号成功注册

**其他问题**

- [x] 账号成功注册后无提示,不会返回到登录界面
- [x] 城市字段过长时文字重合

**版本**

**app**：https://github.com/misterplus/LearnWithEase/commit/442f51be9a1a9b09b491d350fbc7f98c6202c3db

**server**：https://github.com/misterplus/LearnWithEaseServer/commit/a1a87dddb0d0e00847895634af53e257a59ff372

**Comment by misterplus** [comment]
其他问题1已解决

**Comment by debuggerzh** [comment]
无重合问题。只是城市过长时字体水平方向受挤压。

**Comment by misterplus** [comment]
> 无重合问题。只是城市过长时字体水平方向受挤压。

这边测试在城市总文字8-9个时会重合，请二次确认。 @debuggerzh
