### ISSUE TITLE
[Test Report]客户端我的模块

### ISSUE THREAD

**Issue by debuggerzh** [misterplus/LearnWithEase#19]
**简述**

测试客户端“我的”模块

**测试流程**
单次测试流程的所有执行步骤：

0. 登录后，点击“我的”选项卡，进入“我的”页面
1. 点击个人信息右侧箭头（下略），查看个人具体信息
   1. 点击头像，分别选择拍照和从图库选择
   2. 点击以修改昵称
   3. 点击以修改个性签名
   4. 点击以修改性别
   5. 点击以修改年龄
   6. 点击以修改所在城市
   7. 点击以修改教育背景
   8. 点击以修改年级
2. 点击箭头进入修改偏好子页面
   1. 点击以修改自习时长、小憩时长、学习内容、同城优先、同校优先、同性优先、优先加入新房间等偏好
3. 点击箭头进入软件设置->用户设置->修改密码子页面
   1. 输入错误的当前密码，保持新密码和确认密码一致，点击确定观察响应
   2. 输入正确的当前密码，输入不合法的新密码，保持新密码和确认密码一致，点击确定观察响应
   3. 输入正确的当前密码，输入合法的新密码，输入和新密码不一致的确认密码，点击确定观察响应
   4. 输入正确的当前密码，输入合法的新密码，保持新密码和确认密码一致，点击确定观察响应
   
2. 点击退出登录，观察响应

**测试案例**
以成组的方式，分别描述测试数据，测试结果，预期结果

1. 
      |          | 拍照                     | 从图库选择               |
      | -------- | ------------------------ | ------------------------ |
      | 测试结果 | 头像修改成功，但程序卡死 | 头像修改成功，但程序卡死 |
      | 预期结果 | 头像修改成功             | 头像修改成功             |

   该组其余部分的测试结果与预期相符。特别需要指出的是，最大长度（16位）的用户名和个性签名都不会引发显示溢出问题
   
2. 偏好部分的测试结果与预期相符

3. 可以成功退出登录；

  ~~修改密码方面，输入数据后点击确定无任何响应~~
| 当前密码 | 新密码   | 确认密码 | 测试结果       | 预期结果       |
| -------- | -------- | -------- | -------------- | -------------- |
| dkdkfg1  | hkhk1234 | hkhk1234 | 当前密码错误   | 当前密码错误   |
| dkdkfg15 | hkhk     | hkhk     | 密码不合法     | 密码不合法     |
| dkdkfg15 | hkhk1234 | hkhk12   | 两次密码不一致 | 两次密码不一致 |
| dkdkfg15 | hkhk1234 | hkhk1234 | 修改成功       | 修改成功       |

**问题总览**

- [x] 修改头像时程序卡死 
- [x] 修改密码方面，输入数据后点击确定无任何响应
- [x] 城市名长度过长形成重叠
- [x] 城市为直辖市时，文字没有右对齐
- [x] 点击查看验证信息详细页并返回后，会默认同意请求

**其他问题**

- [x] 建议昵称在被修改时保持全选状态，以方便修改
- [x] 软件设置->系统设置部分的间距不一,建议修改使其美观
- [x] 修改信息的按钮后要再点击一次文本框才弹出键盘
- [x] 退出登录之后按手机虚拟按键的返回仍可以返回原页面
- [x] 学校名过长形成重叠

**版本**

**app**：https://github.com/misterplus/LearnWithEase/commit/442f51be9a1a9b09b491d350fbc7f98c6202c3db

**server**：https://github.com/misterplus/LearnWithEaseServer/commit/a1a87dddb0d0e00847895634af53e257a59ff372

**Comment by misterplus** [comment]
其他问题2已解决

**Comment by misterplus** [comment]
其他问题3：不同间距以表示当前行的种类为分类行/内容行，是否有更好的方案来安排UI? @debuggerzh

**Comment by misterplus** [comment]
问题总览1已解决

**Comment by debuggerzh** [comment]
> 其他问题3：不同间距以表示当前行的种类为分类行/内容行，是否有更好的方案来安排UI? @debuggerzh

可以考虑引入二级页面，在系统设置页面中加以区分
