### ISSUE TITLE
[BUG][无法连接服务器的误判]

### ISSUE THREAD

**Issue by debuggerzh** [misterplus/LearnWithEase#2]
**简述**
将不能连接服务器误判为超时

**重现步骤**
重现该Bug所需的步骤：
1. 确保服务器关闭，网络连接正常
2. 提交符合约定的账号密码
3. 点击登录

**预期行为**
提示无法连接到服务器

**实际行为**
提示连接超时

**截图**
![2021-04-21_200824.png](https://i.loli.net/2021/04/21/1mClXh8skpEoP5q.png)

**Comment by bestrappe** [comment]
测试结果：显示“服务器异常，请稍后再试”

**Comment by Le0nidas-wow** [comment]
测试结果：没有获得反馈结果，一直在登陆中状态

**Comment by debuggerzh** [comment]
> 测试结果：没有获得反馈结果，一直在登陆中状态

那不是应该显示超时么，难道连超时也没有，一直转圈？

**Comment by Le0nidas-wow** [comment]
> > 测试结果：没有获得反馈结果，一直在登陆中状态
> 
> 那不是应该显示超时么，难道连超时也没有，一直转圈？

一直转圈，根本停不下来，没有任何提示

**Comment by misterplus** [comment]
> > 测试结果：没有获得反馈结果，一直在登陆中状态
> 
> 那不是应该显示超时么，难道连超时也没有，一直转圈？

是我更改了onException实现后导致的，默认实现没有取消Dialog，正在修改。

**Comment by misterplus** [comment]
Closes with #6
