### ISSUE TITLE
[BUG]长按聊天消息后程序崩溃

### ISSUE THREAD

**Issue by debuggerzh** [misterplus/LearnWithEase#21]
**简述**
在聊天界面长按某条消息，程序崩溃

**重现步骤**
重现该Bug所需的步骤：
1. 点击好友选项卡，点击进入和某位好友的最近聊天
2. 长按某条消息

**预期行为**
弹出对该条消息的处理操作

**实际行为**
程序崩溃

**截图**
![微信图片_20210614221400.jpg](https://i.loli.net/2021/06/14/V7Kb1CiPFj6oQ8M.jpg)

**版本**
将测试时使用的app版本(commit号)粘贴在这里。
app:https://github.com/misterplus/LearnWithEase/commit/3cfd908547f8aa76e4d9957322b3d64f9d413bbf

**问题代码**
如果能够判断问题的大致源头，可以将对应链接粘贴在这里。
根据截图信息，认为
https://github.com/misterplus/LearnWithEase/blob/main/uikit/src/com/netease/nim/uikit/business/session/module/MsgForwardFilter.java

**解决方案**
重写长按方法

**Comment by misterplus** [comment]
On it!

**Comment by misterplus** [comment]
fixed
