### ISSUE TITLE
[BUG][登录模块]网络连接异常的误判

### ISSUE THREAD

**Issue by debuggerzh** [misterplus/LearnWithEase#5]
**简述**
将网络连接异常误判为服务器异常
**重现步骤**
重现该Bug所需的步骤：
1. 关闭虚拟机网络
2. 输入合法用户名和合法密码，点击登录
3. 观察（断网时的）错误提示

**预期行为**
提示网络连接异常

**实际行为**
提示服务器异常
**截图**
![Screenshot_1619051689.png](https://i.loli.net/2021/04/22/pJvVDbeyuohKzaB.png)
![2021-04-22_083721.png](https://i.loli.net/2021/04/22/QYqW81UBM9sH7bo.png)

**版本**

app:https://github.com/misterplus/LearnWithEase/commit/f8894d678422182f00c6ebd81225b2e45a875622
server:https://github.com/misterplus/LearnWithEaseServer/commit/4ffe7b7212b8a35f938cd63162daffa668f0b79c

**Comment by bestrappe** [comment]
测试结果：提示“服务器异常，请稍后再试”

**Comment by misterplus** [comment]
Closes with #9
